$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
display_name: Run inference on LLM
name: dp_transformers_privacy_auditing_inference
type: pipeline

inputs:
  base_model:
    type: uri_folder
  peft:
    type: uri_folder
    optional: true
  data:
    type: uri_file
  per_device_batch_size:
    type: integer
    default: 32
  sequence_len:
    type: integer
    default: 512
  mi_signal_method:
    type: string
    optional: true
  mi_signal_extra_args:
    type: string
    optional: true
  mi_signal_aggregation:
    type: string
    optional: true
  pack_dataset:
    type: boolean
    default: False

outputs:
  predictions:
    type: uri_folder

jobs:
  convert_to_jsonl:
    type: command
    component: ../../../components/convert_hf_dataset_to_jsonl/component_spec.yml
    inputs:
      input: ${{parent.inputs.data}}
      completion_column: "sentence"
    outputs:
      output:
        mode: "rw_mount"
  tokenize:
    type: command
    component: ../../../components/tokenize/component_spec.yml
    inputs:
      tokenizer_path: ${{parent.inputs.base_model}}
      data: ${{parent.jobs.convert_to_jsonl.outputs.output}}
      packed_dataset: ${{parent.inputs.pack_dataset}}
      sequence_len: ${{parent.inputs.sequence_len}}
      chat_format: False
    compute: azureml:D64sv3
    outputs:
      tokenized_data:
        mode: "rw_mount"
  inference:
    type: command
    component: ../../../components/inference/component_spec.yml
    inputs:
      base_model: ${{parent.inputs.base_model}}
      peft: ${{parent.inputs.peft}}
      tokenized_data: ${{parent.jobs.tokenize.outputs.tokenized_data}}
      per_device_batch_size: ${{parent.inputs.per_device_batch_size}}
      mi_signal_method: ${{parent.inputs.mi_signal_method}}
      mi_signal_extra_args: ${{parent.inputs.mi_signal_extra_args}}
      mi_signal_aggregation: ${{parent.inputs.mi_signal_aggregation}}
    outputs:
      predictions: ${{parent.outputs.predictions}}
