$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: parameter_efficient_fine_tuning-epsilon_8

settings:
  default_compute: azureml:ND40rsv2-2

jobs:
  train_model:
    type: command
    component: ../component_spec.yml
    inputs:
      nproc_per_node: 8
      model: ${{inputs.model}}
      sequence_len: 2048
      per_device_train_batch_size: 128
      gradient_accumulation_steps: 1
      evaluation_strategy: steps
      eval_steps: 128
      log_level: info
      per_device_eval_batch_size: 64
      eval_accumulation_steps: 1
      seed: 42
      target_epsilon: 8
      target_delta: 2e-6
      per_sample_max_grad_norm: 1.0
      prediction_loss_only: true
      weight_decay: 0.01
      remove_unused_columns: false
      num_train_epochs: 3
      logging_steps: 5
      max_grad_norm: 0
      lr_scheduler_type: constant
      learning_rate: 1e-4
      disable_tqdm: true
      dataloader_num_workers: 2
      label_names: labels
