$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: SST2-non-dp-sweep
experiment_name: auditing-synthetic-text-generation

settings:
  default_compute: azureml:ND40rsv2

inputs:
  model_path:
    type: uri_folder
    path: "azureml:Mistral-7B-v0point1:1"
  train_data_path:
    type: uri_folder
    path: "azureml:SST2-train:3"
  eval_data_path:
    type: uri_folder
    path: "azureml:SST2-test:3"

jobs:
  preprocess:
    type: command
    component: ./components/preprocess_for_synthesizer/component_spec.yml
    inputs:
      train_data_path: ${{parent.inputs.train_data_path}}
      eval_data_path: ${{parent.inputs.eval_data_path}}
      templated_prompt: "A sentence with a {label} sentiment: "
      label_column: "label"
      text_column: "sentence"
    outputs:
      train_data:
        mode: "rw_mount"
      eval_data:
        mode: "rw_mount"
  fine_tune:
    type: sweep
    inputs:
      train_data_path: ${{parent.jobs.preprocess.outputs.train_data}}
      eval_data_path: ${{parent.jobs.preprocess.outputs.eval_data}}
      evaluation_strategy: "steps"
      eval_steps: 50
      label_names: "labels"
      model_path: ${{parent.inputs.model_path}}
      nproc_per_node: 8
      sequence_len: 128
      gradient_accumulation_steps: 1
      seed: 239023
      chat_format: False
      num_train_epochs: 3.0
      bf16: false
      fp16: false
    outputs:
      output_dir:
        mode: "rw_mount"
    sampling_algorithm: grid
    trial: ../../components/nodp_fine_tune_LLM_w_qlora/component_spec.yml
    search_space:
      per_device_train_batch_size:
        type: "choice"
        values: [8, 16, 32]
      learning_rate:
        type: "loguniform"
        min_value: -13.82
        max_value: -6.91
    objective:
      primary_metric: "eval_loss"
      goal: "minimize"
    limits:
      max_total_trials: 15
  generate:
    type: command
    component: ../../components/llm-synthetic-data-generation/component_spec.yml
    inputs:
      lora_path: ${{parent.jobs.fine_tune.outputs.output_dir}}
      model_path: ${{parent.inputs.model_path}}
      train_data_path: ${{parent.jobs.preprocess.outputs.train_data}}
      nproc_per_node: 8
      batch_size: 32
      seed: 2933
      max_new_tokens: 128
      mixed_precision: "no"
    outputs:
      output_dir:
        mode: "rw_mount"
  compute_utility:
    type: command
    component: ./components/utility_computation/component_spec.yml
    inputs:
      nproc_per_node: 8
      model_name: "roberta-base"
      is_synthetic: true
      train_data_path: ${{parent.jobs.generate.outputs.output_dir}}
      train_label_name: "Prompt"
      train_text_name: "Generation"
      eval_data_path: ${{parent.inputs.eval_data_path}}
      eval_label_name: "label"
      eval_text_name: "sentence"
      sequence_len: 128
      per_device_train_batch_size: 8
      gradient_accumulation_steps: 1
      num_train_epochs: 1
      evaluation_strategy: "steps"
      eval_steps: 100
      save_strategy: "no"
      log_level: info
      seed: 239023
      weight_decay: 0.01
      logging_steps: 10
      learning_rate: 3e-5
    outputs:
      output_dir:
        mode: "rw_mount"
