$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: SST2
experiment_name: auditing-synthetic-text-generation

settings:
  default_compute: azureml:ND96asrv4

inputs:
  model_path: 

jobs:
  preprocess:
    type: command
    component: ./components/preprocess_for_synthesizer/component_spec.yml
    inputs:
      dataset: "azureml:SST2-train:3"
    outputs:
      train_data:
        mode: "rw_mount"
  fine_tune:
    type: command
    component: azureml:dp_fine_tune_llm_w_qlora:5
    inputs:
      train_data_path: ${{parent.jobs.preprocess.outputs.train_data}}
      model_path: ${{inputs.model_path}}
    outputs:
      output_dir:
        mode: "rw_mount"
  generate:
    type: command
    component: azureml:llm_synthetic_data_generation:2
    inputs:
      lora_path: ${{parent.jobs.fine_tune.outputs.output_dir}}
      model_path: ${{inputs.model_path}}
      train_data_path: ${{parent.jobs.preprocess.outputs.train_data}}
