$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline

name: dp_transformers_evaluate_llm
display_name: evaluate_llm
description: "Evaluate a large language model on a suite of benchmarks (MT-Bench)."


inputs:
  model:
    type: uri_folder
    description: "Path to the model to use in HF format."
  num_gpus_per_model:
    type: integer
    description: "Number of GPUs to use per model."
    default: 1
  num_concurrent_oai_api_calls:
    type: integer
    description: "Number of concurrent API calls to the Azure OpenAI API to use."
    default: 1

jobs:
  mt_bench:
    type: command
    component: ./mt_bench/component_spec.yml
    inputs:
      model: ${{parent.inputs.model}}
      num_gpus_per_model: ${{parent.inputs.num_gpus_per_model}}
      num_concurrent_api_calls: ${{parent.inputs.num_concurrent_oai_api_calls}}
