$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: no-DP | no-LoRA| GPT2 | Reddit
experiment_name: dp-transformers-research-dp-llm

inputs:
  base_model:
    type: uri_folder
    path: "azureml:gpt2:1"
  train_data:
    type: uri_file
    path: "azureml:RedditJsonlPromptCompletion100kTrain:1"
  val_data:
    type: uri_file
    path: "azureml:RedditJsonlPromptCompletion100kValidation:1"
  sequence_len: 512

settings:
  default_compute: azureml:ND40rsv2

jobs:
  train:
    type: pipeline
    component: ./subpipelines/train.yml
    inputs:
      base_model: ${{parent.inputs.base_model}}
      train_data: ${{parent.inputs.train_data}}
      val_data: ${{parent.inputs.val_data}}
      seed: 12901
      sequence_len: ${{parent.inputs.sequence_len}}
    outputs:
      model:
        mode: "rw_mount"
  inference:
    type: pipeline
    component: ./subpipelines/inference.yml
    inputs:
      base_model: ${{parent.jobs.train.outputs.model}}
      data: ${{parent.inputs.val_data}}
      mi_signal_method: TaylorSoftMargin
      mi_signal_extra_args: "taylor_n=4 taylor_m=0.6 temp=2.0"
      mi_signal_aggregation: mean
      sequence_len: ${{parent.inputs.sequence_len}}
    outputs:
      predictions:
        mode: "rw_mount"
