$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: evaluate

settings:
  default_compute: azureml:ND96asrv4

jobs:
  evaluation:
    type: pipeline
    component: ../../components/evaluation/all_evaluations.yml
    inputs:
      model: "azureml:llama-2-7b-chat-hf:2"
