$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: evaluate

settings:
  default_compute: azureml:ND40rsv2

inputs:
  base_model:
    type: uri_folder
    path: azureml:llama-2-7b-chat-hf:2

jobs:
  evaluation:
    type: pipeline
    component: ../../components/evaluation/evaluate_llm.yml
    inputs:
      model: ${{parent.inputs.base_model}}
