$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: evaluate
experiment_name: dp-transformer-research-dp-llm

settings:
  default_compute: azureml:ND96asrv4

jobs:
  judge:
    type: command
    component: ../../components/evaluation/mt_bench/_judge.yml
    inputs:
      model_id: phi-2-dpo
      answers: answers.jsonl
      num_concurrent_api_calls: 10
      openai_api_base: "https://ppml.openai.azure.com/"
      openai_api_type: "azure"
      openai_api_key_secret_name: "openai-ppml-key1"
      openai_api_version: "2023-07-01-preview"