$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline

name: dp_transformers_evaluation_mt_bench
display_name: MT-Bench
description: "Evaluate a large language model on a suite of benchmarks (MT-Bench)."


inputs:
  model:
    type: uri_folder
    description: "Path to the model to use in HF format."
  num_gpus_per_model:
    type: integer
    description: "Number of GPUs to use per model."
    default: 1
  num_concurrent_oai_api_calls:
    type: integer
    description: "Number of concurrent API calls to the Azure OpenAI API to use."
    default: 10
  openai_api_base:
    type: string
    description: "Base URL for the OpenAI API."
    default: "https://ppml.openai.azure.com/"
  openai_api_key_secret_name:
    type: string
    description: "Name of the secret containing the OpenAI API key in the Azure key vault associated with this workspace."
    default: "openai-ppml-key1"
  openai_api_type:
    type: string
    description: "Type of the OpenAI API to use."
    default: "azure"
  openai_api_version:
    type: string
    description: "Version of the OpenAI API to use."
    default: "2023-07-01-preview"
outputs:
  results:
    type: uri_file
    description: "Path to the results file."
  judgments:
    type: uri_file
    description: "Path to the judgments file."

jobs:
  generate:
    type: command
    component: ./_generate.yml
    inputs:
      model: ${{parent.inputs.model}}
      num_gpus_per_model: ${{parent.inputs.num_gpus_per_model}}
    outputs:
      answers:
        mode: "rw_mount"
  judge:
    type: command
    component: ./_judge.yml
    inputs:
      answers: ${{parent.jobs.generate.outputs.answers}}
      num_concurrent_api_calls: ${{parent.inputs.num_concurrent_oai_api_calls}}
      openai_api_base: ${{parent.inputs.openai_api_base}}
      openai_api_type: ${{parent.inputs.openai_api_type}}
      openai_api_key_secret_name: ${{parent.inputs.openai_api_key_secret_name}}
      openai_api_version: ${{parent.inputs.openai_api_version}}
    outputs:
      results: ${{parent.outputs.results}}
      judgments: ${{parent.outputs.judgments}}
