$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
name: dp-transformers-evaluation-open-llm-benchmark
display_name: Open LLM Benchmark
description: |
  Evaluate a model on the Open LLM Leaderboard benchmarks.

  Tasks:
    - ARC Challenge
    - Hellaswag
    - TruthfulQA
    - MMLU
    - Winogrande
    - GSM8k

type: pipeline

inputs:
  model:
    type: uri_folder
    description: "Path to the model to use in HF format."
    mode: "download"
  peft:
    type: uri_folder
    description: "Path to the PEFT weights"
    optional: true
  batch_size:
    type: string
    description: "Batch size to use for evaluation"
    default: "auto:8"
  trust_remote_code:
    type: boolean
    optional: true
    description: Trust remote code (e.g. from HuggingFace) when loading the model.
outputs:
  results:
    type: uri_folder
    description: "Path to the results file"

jobs:
  arc_challenge:
    type: command
    component: ../lm_eval/component_spec.yml
    inputs:
      model: ${{parent.inputs.model}}
      peft: ${{parent.inputs.peft}}
      tasks: "arc_challenge"
      num_fewshot: 25
      batch_size: ${{parent.inputs.batch_size}}
      trust_remote_code: ${{parent.inputs.trust_remote_code}}
    outputs:
      results:
        mode: "rw_mount"
  hellaswag:
    type: command
    component: ../lm_eval/component_spec.yml
    inputs:
      model: ${{parent.inputs.model}}
      peft: ${{parent.inputs.peft}}
      batch_size: ${{parent.inputs.batch_size}}
      num_fewshot: 10
      tasks: "hellaswag"
      trust_remote_code: ${{parent.inputs.trust_remote_code}}
    outputs:
      results:
        mode: "rw_mount"
  truthfulqa_mc2:
    type: command
    component: ../lm_eval/component_spec.yml
    inputs:
      model: ${{parent.inputs.model}}
      peft: ${{parent.inputs.peft}}
      batch_size: ${{parent.inputs.batch_size}}
      num_fewshot: 0
      tasks: "truthfulqa_mc2"
      trust_remote_code: ${{parent.inputs.trust_remote_code}}
    outputs:
      results:
        mode: "rw_mount"
  mmlu:
    type: command
    component: ../lm_eval/component_spec.yml
    inputs:
      model: ${{parent.inputs.model}}
      peft: ${{parent.inputs.peft}}
      batch_size: ${{parent.inputs.batch_size}}
      num_fewshot: 5
      tasks: "mmlu"
      trust_remote_code: ${{parent.inputs.trust_remote_code}}
    outputs:
      results:
        mode: "rw_mount"
  winogrande:
    type: command
    component: ../lm_eval/component_spec.yml
    inputs:
      model: ${{parent.inputs.model}}
      peft: ${{parent.inputs.peft}}
      batch_size: ${{parent.inputs.batch_size}}
      num_fewshot: 5
      tasks: "winogrande"
      trust_remote_code: ${{parent.inputs.trust_remote_code}}
    outputs:
      results:
        mode: "rw_mount"
  gsm8k:
    type: command
    component: ../lm_eval/component_spec.yml
    inputs:
      model: ${{parent.inputs.model}}
      peft: ${{parent.inputs.peft}}
      batch_size: ${{parent.inputs.batch_size}}
      num_fewshot: 5
      tasks: "gsm8k"
      trust_remote_code: ${{parent.inputs.trust_remote_code}}
    outputs:
      results:
        mode: "rw_mount"
  collect_results:
    type: command
    component: ./_collect_results.yml
    inputs:
      arc_challenge: ${{parent.jobs.arc_challenge.outputs.results}}
      hellaswag: ${{parent.jobs.hellaswag.outputs.results}}
      truthfulqa_mc2: ${{parent.jobs.truthfulqa_mc2.outputs.results}}
      mmlu: ${{parent.jobs.mmlu.outputs.results}}
      winogrande: ${{parent.jobs.winogrande.outputs.results}}
      gsm8k: ${{parent.jobs.gsm8k.outputs.results}}
    outputs:
      results: ${{parent.outputs.results}}